### ISSUE TITLE
automated benchmark tool

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-go-driver#237]
Benchmark requirements / matrix

* Each run needs to be run 5 times
  * we take the mean as the result
  * wa calculate stddev to make sure there are no environmental issues
* Workload: inserts, mixed
* Tasks: 1M 10M 100M
* Contenders: Rust, Gocql, This
  * workers: 1K, 2K, 4K, 8K
* Contenders: This in **async** mode
  * workers: nr CPUs * 2^i for i=0-4
  * batch size: 256*2^i for i=0-4

**Comment by Kulezi** [comment]
Closed as of #241
