### ISSUE TITLE
session: add log configuration

### ISSUE THREAD

**Issue by Kulezi** [scylladb/scylla-go-driver#271]
Right now the driver logs important events to stderr, it should be off by default and configurable by the user through sessionConfig.

Maybe using an interface like gocql: https://github.com/gocql/gocql/blob/v1.2.0/logger.go#L9
or https://github.com/scylladb/go-log

**Comment by martin-sucha** [comment]
I'd prefer some kind of interface where I can plug a custom implementation. We have an internal logging package (based on zap) that always adds some custom fields.

The driver should also log query warnings by default to the configured logger and allow users to explicitly turn the warnings off if needed. That would make warnings more useful. With gocql probably most people ignore them. (but maybe this is for a separate issue?)
